// url-index.mjs — regenerate references/url-database.md from the content
// collection so internal-linking always targets live, current URLs.
//   node scripts/url-index.mjs
// Reads published posts' frontmatter directly (no build needed).

import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const POSTS = path.join(ROOT, 'src/content/posts');
const OUT = path.join(ROOT, 'references/url-database.md');

const walk = (d) =>
	fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => {
		const p = path.join(d, e.name);
		return e.isDirectory() ? walk(p) : p;
	});

const field = (fm, key) => {
	const m = fm.match(new RegExp(`^${key}:\\s*(.+)$`, 'm'));
	return m ? m[1].trim().replace(/^['"]|['"]$/g, '') : '';
};

const PILLARS = ['style', 'beauty', 'dining', 'travel', 'culture', 'living', 'people', 'guides'];
const byCat = Object.fromEntries(PILLARS.map((p) => [p, []]));

for (const file of walk(POSTS).filter((f) => /\.(md|mdx)$/.test(f))) {
	const src = fs.readFileSync(file, 'utf8');
	const fm = src.split('---')[1] ?? '';
	if (/^draft:\s*true/m.test(fm)) continue;
	const category = field(fm, 'category');
	if (!byCat[category]) continue;
	const slug = path.basename(file).replace(/\.(md|mdx)$/, '');
	byCat[category].push({
		title: field(fm, 'title'),
		url: `/${category}/${slug}/`,
		standfirst: field(fm, 'standfirst'),
	});
}

const total = Object.values(byCat).reduce((n, a) => n + a.length, 0);
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
let md = `# URL database — live internal-link inventory

> Generated by \`scripts/url-index.mjs\` from the content collection. Do not edit
> by hand. ${total} published posts. Use these for the 5–8 internal links per
> article (see the arahkaii-internal-linking skill).

`;
for (const p of PILLARS) {
	const items = byCat[p];
	if (!items.length) continue;
	md += `## ${cap(p)} (${items.length})\n\n`;
	for (const it of items.sort((a, b) => a.title.localeCompare(b.title))) {
		md += `- [${it.title}](${it.url})${it.standfirst ? ` — ${it.standfirst}` : ''}\n`;
	}
	md += '\n';
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, md);
console.log(`✓ wrote references/url-database.md — ${total} posts across ${PILLARS.filter((p) => byCat[p].length).length} pillars`);
